from pathlib import Path
r=Path(__file__).resolve().parents[1];t=Path('/home/nmaldaner/.claude/skills/formato-curso-v6/assets/landing-template.html').read_text()
values={'[Nome do curso]':'Motion Echo v6 — Retratos com eco de movimento','[1 frase: o que a pessoa sai fazendo]':'Aprenda a criar e revisar quatro estilos de retrato com eco de movimento em quatro aulas práticas.','[Nome curto]':'Motion Echo v6','[Categoria — ex.: IA no seu trabalho]':'Motion Echo v6 · Retratos com IA','[Promessa em <em>poucas palavras</em>]':'Um rosto nítido.<br><em>Quatro formas de movimento.</em>','[O que a pessoa sai fazendo, em 1–2 frases. Sem vídeo, no seu tempo.]':'Prepare sua referência, crie quatro estilos e revise cada resultado. Violeta, ciano, escarlate e azul em aulas práticas, no seu ritmo.','[N]':'4','[alt da trilha]':'Fotógrafa e profissional de redes sociais comparam retratos com diferentes cores e rastros.','[Resultado 1]':'Preparar a referência','[em uma linha, concreto]':'Escolher uma foto nítida e autorizada.','[Resultado 2]':'Criar quatro efeitos','[Resultado 3]':'Revisar com critério','[profissão-alvo 1] e quer [resultado].':'Fotografa pessoas ou trabalha com redes sociais e quer criar retratos editoriais.'}
for a,b in values.items():t=t.replace(a,b)
t=t.replace('[…]','Usar pedidos claros e fazer uma mudança por tentativa.',1).replace('[…]','Conferir rosto, cor e direção do rastro.',1)
t=t.replace('sem instalar nada','prática na ferramenta de imagens que você já usa')
t=t.replace('<section class="l-sec">\n    <h2>Para quem é</h2>','<section class="l-sec"><h2>Antes de começar</h2><p>Tenha uma foto sua ou autorizada e acesso a uma ferramenta que aceite imagem de referência. O curso é aberto e gratuito. A ferramenta escolhida pode ter condições próprias de uso.</p><p>As ilustrações foram geradas com pessoas fictícias. Os exemplos não comprovam preservação de identidade. A espera pela geração pode passar do tempo previsto para a prática.</p><p><a href="guia/index.html">Consultar o guia e os quatro pedidos originais</a></p></section>\n<section class="l-sec">\n    <h2>Para quem é</h2>')
t=t.replace('<!-- LANDING formato-curso v6 — usa assets/aula.css (mesmos tokens, tema papel).\n     A lista de aulas entre os marcadores AULAS é preenchida pelo montar-curso.py. Troque os [ ]. -->','')
(r/'landing.html').write_text(t)
(r/'index.html').write_text('<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="refresh" content="0;url=landing.html"><title>Motion Echo v6</title><a href="landing.html">Abrir Motion Echo v6</a><script>location.replace("landing.html"+location.search+location.hash)</script></html>')
