from pathlib import Path
import html,json
r=Path(__file__).resolve().parents[1]
def esc(s):return html.escape(s)
def pair(a,b,x,y):return f'<figure class="largo"><div class="lado"><div class="neutro"><span class="rot">{a}</span><p>{x}</p></div><div class="bom"><span class="rot">{b}</span><p>{y}</p></div></div><figcaption>Compare as instruções pelos rótulos. Este quadro não é uma medição de resultados.</figcaption></figure>'
def window(items,caption):return '<figure class="largo"><div class="janela"><div class="tela-top"><span>Roteiro de revisão</span></div><div class="janela-body">'+''.join(f'<div class="item doc"><span class="pin">{i}</span>{v}</div>' for i,v in enumerate(items,1))+f'</div></div><figcaption>{caption}</figcaption></figure>'
def chat(a,b):return f'<figure class="largo"><div class="tela"><div class="tela-top"><span>Pedidos de exemplo · tela ilustrativa</span></div><div class="tela-caso" data-rotulo="Pedido aberto"><div class="tela-body"><p class="msg eu"><span class="quem">Você</span>{a}</p></div><p class="tela-nota">Faltam critérios para revisar o resultado.</p></div><div class="tela-caso" data-rotulo="Pedido delimitado"><div class="tela-body"><p class="msg eu"><span class="quem">Você</span>{b}</p></div><p class="tela-nota bom">Rosto, cor e posição do efeito ficam definidos.</p></div></div><figcaption>Toque nos dois casos. São pedidos didáticos, sem resposta inventada da ferramenta.</figcaption></figure>'
base='Use a foto anexada como única referência da pessoa. Preserve suas feições, idade aparente e penteado. Deixe olhos, nariz e boca do rosto principal nítidos. Faça um retrato vertical 9:16, com roupa escura simples e fundo escuro. '
end=' Não acrescente texto, logotipos, acessórios ou outras cores neon. Mantenha o rastro separado dos olhos, nariz e boca. Preserve a textura natural da pele.'
lessons=[dict(
title='Um rosto nítido sustenta o eco violeta',slug='violeta',promise='Você consegue preparar uma foto de referência e criar sua primeira tentativa de retrato violeta.',why='Um rastro bonito pode esconder uma pessoa irreconhecível. Comece protegendo o rosto. Depois você controla o efeito.',
minute=['Use uma foto nítida e autorizada.','Peça violeta e apenas um perfil residual.','Compare o rosto gerado com a foto original.'],
steps=[('A referência mostra quem deve continuar na imagem','Uma <span class="gterm" data-def="É a foto que orienta a aparência da pessoa. Ela não garante que a ferramenta preserve todas as feições.">foto de referência</span> precisa mostrar olhos, nariz e boca. Escolha uma imagem sua ou autorizada. Evite óculos escuros e mãos cobrindo o rosto.','fotógrafa','Lia fotografa artistas para divulgação. Ela escolhe um retrato frontal autorizado, com cabelo e olhos visíveis.',window(['Rosto visível, sem objeto cobrindo a boca','Foto nítida quando você amplia','Autorização para usar a imagem'],'Confira estes três pontos na sua própria foto.')),
('O pedido limita o efeito ao redor do rosto','O <span class="gterm" data-def="É uma cópia suave que sugere uma posição anterior da cabeça. Deve pertencer ao mesmo movimento.">eco de movimento</span> fica atrás da posição principal. Escreva uma cor e uma direção para o rastro. Não peça várias luzes neon de uma vez.','profissional de redes sociais','Davi prepara a divulgação de uma cantora. Ele troca um pedido genérico por uma instrução com rosto nítido e um eco violeta.',chat('Faça um retrato cheio de efeitos.','Preserve meu rosto. Use violeta e fundo escuro. Coloque um único perfil suave atrás da cabeça. Mantenha olhos, nariz e boca nítidos.')),
('Um resultado bonito ainda precisa de comparação','Amplie a foto original e a versão gerada. Confira o formato dos olhos, o nariz e a boca. Se mudaram, volte à referência original. Reduza o efeito antes de insistir.','fotógrafa','Lia percebe que o nariz ficou diferente. Ela rejeita a versão, mesmo gostando da cor violeta.',pair('Efeito atraente','Rosto aprovado','O rastro chama atenção, mas isso não confirma a identidade.','A pessoa continua reconhecível quando você compara as feições.'))],
effect='Use violeta como cor dominante. Acrescente um perfil ampliado, suave e translúcido atrás da cabeça. Esse perfil sugere uma virada anterior. Mantenha luz no contorno do cabelo e sombras profundas. Use granulação discreta.',
practice='Crie uma tentativa violeta e registre se o rosto foi preservado.',done='Você preparou uma referência e avaliou sua primeira tentativa violeta.',calm='Não encontrou onde anexar a foto? Procure o botão de imagem ou o símbolo de clipe. Os nomes mudam entre ferramentas. Sem essa função, guarde o pedido em Notas e retome a prática quando tiver uma ferramenta compatível.',
checks=['Copie o pedido. Cole na ferramenta que aceita uma foto de referência.','Anexe sua foto autorizada, selecione 9:16 quando disponível e gere uma tentativa.','Compare olhos, nariz e boca. Anote no papel ou em Notas: aprovado ou precisa de correção.'],
cola=['Foto nítida e autorizada.','Uma cor e um perfil suave.','Identidade vem antes do efeito.'],next='Na próxima aula, você vai limitar a dissolução às bordas do retrato.',
cards=[('Uma versão ficou bonita, mas o nariz mudou. Você mantém?','Não. Retome a foto original e reduza a força do efeito.'),('Uma referência esconde os olhos. Qual escolha vem antes da geração?','Trocar por uma foto nítida com as feições visíveis.'),('O retrato ganhou três cores fortes. Que decisão simplifica a correção?','Escolher apenas violeta como cor dominante.')]),
dict(title='O ciano dissolve as bordas, preservando a frente',slug='ciano',promise='Você consegue criar uma tentativa ciano com rastros fora do centro do rosto.',why='Pedir desfoque sem limite pode apagar a expressão. Nesta aula, o movimento começa na silhueta. O centro do rosto continua legível.',minute=['Retome sua foto original.','Reserve a dissolução ao cabelo e ao ombro.','Confira se o rastro atravessou alguma feição.'],
steps=[('A silhueta define onde o efeito pode começar','A <span class="gterm" data-def="É o contorno externo da cabeça e do corpo. Não inclui os olhos, o nariz ou a boca.">silhueta</span> separa a pessoa do fundo. Peça o efeito no cabelo e no ombro. Não use toda a face como área de dissolução.','profissional de redes sociais','Davi prepara um retrato para um perfil musical. Ele mantém a expressão legível e concentra as linhas atrás do cabelo.',pair('Área preservada','Área do efeito','Olhos, nariz, boca e pele da frente do rosto.','Contorno do cabelo e borda do ombro voltada para trás.')),
('Uma cor dá unidade ao retrato','Ciano é um azul esverdeado. Use essa cor como luz dominante e mantenha sombras escuras. Variações claras e escuras da mesma família não exigem outras cores neon.','fotógrafa','Lia cria uma proposta fria para uma banda. Ela mantém o ciano e pede menos brilho no fundo.',chat('Desfaça o rosto em várias cores.','Use ciano como cor dominante. Dissolva apenas o contorno posterior do cabelo e do ombro. Preserve o centro do rosto.')),
('O rastro precisa terminar antes das feições','Veja onde as linhas começam. Se cruzam a boca ou os olhos, o limite falhou. Peça menos intensidade e uma área menor. Use a foto original novamente se a pessoa mudou.','profissional de redes sociais','Davi encontra linhas sobre o olho principal. Ele restringe o efeito à borda do cabelo antes de escolher a imagem.',window(['Olhos e boca continuam legíveis','Linhas aparecem no contorno posterior','Uma família de cor domina o retrato'],'Leia o rosto antes de avaliar a beleza das linhas.'))],
effect='Use ciano como cor dominante. A pessoa olha levemente para cima. Dissolva somente o contorno posterior do cabelo e do ombro em linhas horizontais finas. O centro do rosto deve permanecer inteiro e nítido. Deixe espaço escuro para os rastros.',practice='Gere uma tentativa ciano e delimite a área do efeito.',done='Você criou uma tentativa ciano e conferiu se as linhas respeitam o rosto.',calm='O efeito veio forte demais? Escreva: reduza a dissolução e aplique apenas no contorno do cabelo. Faça uma mudança por tentativa.',checks=['Copie o pedido e cole na ferramenta. Use a mesma foto original ou outra foto autorizada e nítida.','Anexe a foto e gere uma tentativa ciano. Não use a imagem violeta como referência de identidade.','Amplie o rosto e registre onde as linhas começam. Se necessário, peça a correção indicada.'],cola=['Ciano domina a luz.','Dissolução começa na silhueta.','Uma correção por tentativa.'],next='Na próxima aula, você vai aumentar a intensidade sem transformar tudo em ruído.',cards=[('O rastro cobre a boca. Qual limite precisa mudar?','Restrinja a dissolução ao contorno do cabelo e ao ombro.'),('Você tem a imagem violeta e a foto original. Qual usar agora?','A foto original, para evitar acumular mudanças na pessoa.'),('Ciano claro e ciano escuro quebram a regra de uma cor?','Não. São variações da mesma família de cor.')]),
dict(title='O escarlate ganha força com um rastro controlado',slug='escarlate',promise='Você consegue criar uma tentativa escarlate e corrigir um excesso de arraste.',why='Um efeito intenso não precisa ocupar a imagem inteira. O contraste aparece quando parte do retrato fica nítida. Você vai escolher onde aumentar a força.',minute=['Use a foto original como referência.','Escolha uma família quente: vermelho e âmbar.','Mude apenas uma característica por tentativa.'],
steps=[('O arraste aparece na borda da figura','O <span class="gterm" data-def="É um efeito que alonga pequenos fragmentos da imagem. Aqui, ele começa no cabelo ou na roupa.">arraste de pixels</span> lembra pequenos fragmentos esticados. Peça esse efeito na borda do cabelo ou da roupa. Mantenha a face principal intacta.','fotógrafa','Lia prepara uma imagem para o cartaz de um show. Ela concentra o arraste no casaco para manter a expressão reconhecível.',pair('Face principal','Borda em movimento','Pele e feições nítidas continuam sendo a referência.','Fragmentos alongados saem do cabelo ou da roupa.')),
('Vermelho e âmbar formam uma família quente','Escolha escarlate como cor dominante. Pequenos reflexos âmbar podem acompanhar essa luz. Não acrescente ciano ou violeta na mesma tentativa. A roupa escura ajuda o rosto a se destacar.','profissional de redes sociais','Davi recebe um retrato com luzes vermelhas, verdes e azuis. Ele mantém apenas a família vermelha para a divulgação do músico.',chat('Coloque todos os efeitos e cores.','Use vermelho como cor dominante, com pequenos reflexos âmbar. Concentre o arraste na borda do casaco. Preserve o rosto principal.')),
('Uma correção isolada mostra o que melhorou','Mudar cor, pose e rastro ao mesmo tempo impede uma comparação clara. Escolha apenas um problema. Escreva o que deve permanecer e o que deve mudar.','fotógrafa','Lia gosta da luz, mas o cabelo mudou. Ela abre um novo pedido e anexa somente a foto original. Então repete o pedido escarlate e acrescenta a correção.',window(['Escolha um problema: cabelo alterado','Preserve a luz vermelha e a roupa','Retome a foto original e corrija o penteado'],'O registro explica por que você prefere a próxima tentativa.'))],
effect='Use escarlate como cor dominante, com pequenos reflexos âmbar. Crie luz lateral e sombras profundas. Alongue fragmentos da borda do cabelo e da roupa em rastros horizontais. Não arraste o rosto principal. Preserve exatamente o penteado da referência.',practice='Gere uma tentativa escarlate e formule uma correção específica.',done='Você avaliou o arraste escarlate e escreveu um ajuste verificável.',calm='Não sabe qual defeito corrigir primeiro? Compare olhos, nariz e boca com a referência. Depois confira cabelo e idade aparente. Só então ajuste o rastro.',checks=['Copie o pedido, cole na ferramenta e anexe uma foto original autorizada.','Gere uma tentativa escarlate. Anote um único ponto que precisa melhorar.','Abra um novo pedido e anexe somente a foto original. Cole o pedido escarlate e acrescente: reduza o arraste e limite-o à borda do casaco. Confira a nova versão. Se já estava adequado, registre por que manteria a primeira.'],cola=['Família quente sem cores concorrentes.','Arraste fica na borda.','Uma mudança permite comparar.'],next='Na próxima aula, você cria o efeito azul e escolhe as imagens da sua série.',cards=[('Cor, pose e cabelo mudaram juntos. Por que fica difícil revisar?','Não é possível saber qual mudança resolveu ou criou o problema.'),('O cabelo ficou diferente, mas a iluminação agradou. O que pedir?','Preservar a iluminação e retomar o penteado da foto original.'),('A pele desapareceu sob fragmentos. Como limitar o efeito?','Concentrar o arraste na borda da roupa ou do cabelo.')]),
dict(title='O azul fecha a série com um movimento contínuo',slug='azul',promise='Você consegue criar uma tentativa azul e selecionar suas versões aprovadas para uma série.',why='O último efeito parece uma virada capturada pela câmera. A imagem é gerada, mas precisa ter uma lógica visual. Depois você decide quais versões realmente funcionam.',minute=['Use um rastro suave, sem blocos de pixels.','Compare a identidade em cada versão.','Guarde apenas imagens que passam pelos critérios.'],
steps=[('A virada deixa uma posição anterior','A <span class="gterm" data-def="Na fotografia, registra luz durante mais tempo. Aqui, o pedido apenas imita a aparência de uma virada.">longa exposição</span> é uma referência visual para o efeito. Peça um rosto principal nítido e um eco suave. Evite pedir várias pessoas ou cabeças independentes.','profissional de redes sociais','Davi prepara a última opção para o músico. Ele pede uma virada contínua e deixa a segunda silhueta bem apagada.',pair('Arraste digital','Virada contínua','Fragmentos alongados tornam o efeito mais quebrado.','Um eco suave sugere uma posição anterior da cabeça.')),
('O molde fica pronto quando você escolhe as opções','O pedido abaixo já usa azul elétrico e casaco escuro. Você pode trocar a roupa por moletom. Preserve uma cor dominante e evite mudar outros detalhes na mesma tentativa.','fotógrafa','Lia usa um casaco escuro para o retrato final. Ela mantém a mesma foto original que orientou os outros estilos.',chat('Azul ou laranja, casaco ou moletom, vários rastros.','Azul elétrico, casaco escuro e um eco suave. Preserve a pessoa da foto. O rosto principal fica nítido.')),
('A série exige quatro aprovações individuais','Compare cada imagem com a foto original, não apenas com as outras versões. Confira rosto, cor e direção do movimento. Se uma imagem falha, refaça somente essa opção.','profissional de redes sociais','Davi aprova três versões e rejeita uma com olhos alterados. Ele guarda as três e corrige a versão restante.',window(['Violeta: rosto reconhecível e perfil suave','Ciano: linhas fora do centro do rosto','Escarlate: arraste nas bordas','Azul: eco contínuo ligado à mesma pessoa'],'São critérios de escolha, não uma avaliação automática.'))],
effect='Use azul elétrico como cor dominante e um casaco escuro. A pessoa aparece em três quartos, com queixo levemente elevado. Crie um único eco suave e translúcido da cabeça e dos ombros, como resíduo de uma virada. O rastro é contínuo, sem blocos de pixels. Um brilho azul atrás da cabeça desaparece nas bordas escuras.',practice='Gere a versão azul e selecione as imagens aprovadas.',done='Você revisou a tentativa azul e registrou quais versões aprovou ou precisa refazer.',calm='Não fez as aulas anteriores? Comece pela imagem azul. Depois use os pedidos das aulas 1, 2 e 3 com a mesma referência original.',checks=['Copie o pedido, cole na ferramenta e anexe sua foto autorizada. Gere uma tentativa azul.','Compare o resultado com a referência. Confira feições, penteado e o eco contínuo.','Use a opção salvar ou baixar em cada resultado. Abra os arquivos salvos na galeria ou pasta de imagens do aparelho. Em Notas, escreva as quatro cores e marque aprovada ou refazer para cada uma. Se faltam versões, registre pendente.'],cola=['Eco suave sugere a virada.','Cada imagem passa por revisão.','Série coerente começa na referência.'],next='Seu próximo projeto: escolha uma pessoa autorizada e repita a série, mantendo os critérios.',cards=[('O eco parece outra pessoa parada. Qual mudança ajuda?','Use apenas um eco mais transparente e ligado à mesma virada.'),('Três imagens passaram e uma falhou. É preciso refazer todas?','Não. Corrija somente a que falhou, usando a referência original.'),('Uma simulação de longa exposição comprova uma captura com câmera?','Não. O pedido descreve a aparência de uma imagem gerada.')])]
for n,d in enumerate(lessons,1):
 if n<4:d['checks'][-1]+=' Use a opção salvar ou baixar da ferramenta para guardar o resultado no aparelho.'
 s=f'<section class="view" id="v-aula-{n}" data-aula="{n}" data-tempo="15min"><div class="aula"><header class="a-hero"><p class="kicker">Aula {n} de 4</p><h1>{d["title"]}</h1><figure class="cena"><img src="assets/img/aula-{n}.webp" width="1280" height="720" alt="Profissional revisa um retrato {d["slug"]} para decidir como preservar o rosto e controlar o movimento."><figcaption>Cena ilustrativa gerada com IA. Não é registro de uso de uma ferramenta.</figcaption></figure><p class="promise">{d["promise"]}</p><p class="why">{d["why"]}</p><div class="em1min"><p class="k">Em 1 minuto</p><ol>'+''.join(f'<li>{x}</li>' for x in d['minute'])+'</ol></div></header>'
 for i,(title,body,prof,example,visual) in enumerate(d['steps'],1):
  s+=f'<section class="step" data-kind="fundamento"><h2><span class="n">{i}</span>{title}</h2><p>{body}</p><p data-ex="{prof}">{example}</p>{visual}'
  if (i==2 and n<3) or (i==1 and n>=3):s+=f'<figure><img src="assets/img/{d["slug"]}.webp" width="480" height="853" style="display:block;max-width:100%;height:auto;margin:auto" loading="lazy" alt="Exemplo de retrato {d["slug"]} com rosto nítido e rastro controlado."><figcaption>Ilustração gerada com pessoa fictícia. Demonstra o estilo; não testa a preservação de uma pessoa real.</figcaption></figure>'
  if i==3:
   s+=f'<div class="calma"><p><span class="k">Se travou aqui, é normal</span>{d["calm"]}</p></div>'
   if n==1:s+='<div class="quiz" data-answer="b"><p class="qk">Teste-se</p><p class="q">O retrato ganhou olhos diferentes. Qual é a melhor próxima ação?</p><button class="opt" data-k="a" data-fb="Mais brilho não corrige as feições alteradas.">Aumentar o brilho do efeito.</button><button class="opt" data-k="b" data-fb="A referência original e menos efeito ajudam a recuperar as feições.">Retomar a foto e reduzir o efeito.</button><button class="opt" data-k="c" data-fb="Recortar não recupera a identidade perdida.">Recortar apenas o centro da imagem.</button><p class="qfb" aria-live="polite"></p></div>'
  s+='</section>'
 s+=f'<section class="practice" data-mode="prompt"><p class="pk">Pratique agora <span class="pcount">0/3</span></p><h3 class="ph">{d["practice"]}</h3><p class="pgoal">Cerca de 10 minutos, no celular ou no computador. Termine com uma tentativa revisada e uma observação anotada.</p><p class="psafe">Use uma foto sua ou autorizada. Confira as condições da ferramenta antes de gerar. Não publique o teste antes de revisar. Se não puder gerar agora, guarde o pedido em Notas. Retome depois; não marque os passos de geração como concluídos. Sem a referência original, a ilustração permite avaliar apenas cor, nitidez e posição do rastro.</p><div class="pcodewrap"><button class="pcopy" type="button">copiar</button><pre class="pcode">{esc(base+d["effect"]+end)}</pre></div><ol class="psteps">'+''.join(f'<li><label><input type="checkbox" data-ptask="{i}"><span>{x}</span></label></li>' for i,x in enumerate(d['checks'],1))+f'</ol><p class="pdone">{d["done"]}</p></section>'
 s+='<div class="fecho"><div class="cola"><p class="k">Cola da aula</p><h3>Três pontos para guardar</h3><ol>'+''.join(f'<li><span>{x}</span></li>' for x in d['cola'])+f'</ol></div><div class="next-action"><p class="nak">Seu próximo passo</p><p class="na-win">Você já conhece os critérios para revisar o retrato {d["slug"]}.</p><p class="na-action">Se gerou, guarde sua tentativa revisada. Se apenas salvou o pedido, retome a prática quando tiver uma ferramenta compatível.</p><p class="na-hook">{d["next"]}</p></div></div>'
 s+='<details class="complementar"><summary>Material complementar<small>Consulta opcional, fora do tempo da prática.</small></summary><section class="comp-sec"><h3>Pedidos originais e referência</h3><p>Os pedidos desta aula são adaptações didáticas em português. O guia preserva os quatro pedidos originais em inglês, fornecidos a partir do material AVCC · AI Video Creators.</p><p><a href="guia/index.html#prompts">Abrir os quatro pedidos originais</a></p><p>As profissões e situações descritas são exemplos didáticos. O tempo de geração depende da ferramenta. Se a espera passar de dez minutos, termine a revisão quando a imagem ficar pronta.</p></section></details>'
 s+=f'<nav class="lnav"><a href="#trilha">voltar à trilha</a><a class="next" href="'+(f'#aula-{n+1}' if n<4 else '#trilha')+'">'+('próxima aula' if n<4 else 'rever a trilha')+f'</a></nav><p class="aula-pe">Aula {n} · Motion Echo v6 · INEMA.CLUB PRO</p></div><script type="application/json" id="cards-{n}">'+json.dumps([dict(front=a,back=b) for a,b in d['cards']],ensure_ascii=False)+'</script></section>'
 (r/f'aulas/aula-{n}.html').write_text(s)
cfg={'id':'motion-echo-v6','titulo':'Motion Echo v6 — Retratos com eco de movimento','titulo_html':'Um rosto nítido. <em>Quatro formas de movimento.</em>','curso_curto':'Motion Echo v6','kicker':'Motion Echo v6 · 4 aulas práticas','lead':'Crie e revise quatro estilos de retrato: violeta, ciano, escarlate e azul. Uma foto de referência, uma cor por imagem e um ajuste por tentativa.','imagem_trilha':'assets/img/trilha.webp','alt_trilha':'Fotógrafa e profissional de redes sociais comparam quatro retratos coloridos para escolher uma série coerente.','rodape':'Motion Echo v6 · INEMA.CLUB PRO · <a href="landing.html">sobre o curso</a>','landing':'landing.html','modulos':[{'titulo':'1. Preserve o rosto','resumo':'Escolha uma referência e delimite o efeito.','aulas':[1,2]},{'titulo':'2. Controle e selecione','resumo':'Ajuste a intensidade e revise sua série.','aulas':[3,4]}]}
(r/'curso.json').write_text(json.dumps(cfg,ensure_ascii=False,indent=2)+'\n')
(r/'context/curriculo.md').write_text('''# Motion Echo v6 — currículo

Formato v6 escolhido explicitamente pelo usuário. Pergunta de descoberta enviada; sem resposta adicional, público provisório informado na conversa: profissionais iniciantes que usam celular, computador e ferramenta de imagens com referência. Duas profissões: Lia, fotógrafa de 36 anos, e Davi, profissional de redes sociais de 54 anos. Exemplos fictícios. Objetivo: criar quatro tentativas revisadas e escolher versões aprovadas para uma série. Quatro sessões de aproximadamente 15 minutos, incluindo prática de 10 minutos. A espera do gerador pode exceder esse tempo.

1. Rosto nítido e eco violeta — preparar foto e gerar primeira tentativa; prática prompt; gancho: delimitar a dissolução.
2. Ciano nas bordas — criar dissolução com rosto legível; prática prompt; gancho: controlar efeito intenso.
3. Arraste escarlate — gerar e escrever uma correção isolada; prática prompt; gancho: completar e selecionar a série.
4. Virada azul — criar tentativa azul e selecionar versões; prática prompt; gancho: repetir com outra referência autorizada.

Fontes: Markdown fornecido e quatro prompts originais enviados pelo usuário, atribuídos a AVCC · AI Video Creators. Ilustrações novas com pessoas fictícias; não servem como evidência de preservação de identidade real. Sem parâmetros inventados de ferramenta. Aulas independentes e sem exigir aulas anteriores para iniciar.

Anti-clone: consultado curso-codex-18-v6. Não reutilizados personagens, cenas ou conteúdo técnico daquele curso.
''')
print('4 aulas e currículo escritos')
